Tested with set -e, grep now works as expected

diff --git a/add-stackstorm-user b/add-stackstorm-user
--- a/add-stackstorm-user
+++ b/add-stackstorm-user
@@ -1,8 +1,13 @@
 #!/bin/bash
 
+# Add user with specified uid and ssh-key.
+#
+# NOTE: The script will return a non-zero status on failure.
+
 set -e
 
 fail() {
+  echo "FAILED!"
   exit 2
 }
 
@@ -18,16 +23,14 @@ fi
 
 user=$1
 uid=$2
-fn=$3
-key=$4
+key=$3
 
 gid=$uid
 
 # Add user, but only if it doesn't already exist
-grep $user /etc/passwd
-if [ $? -ne 0 ]; then
+if ! grep -q $user /etc/passwd; then
   sudo addgroup --gid $uid $user
-  sudo adduser --uid $uid --gid $gid --shell /bin/bash --disabled-password --gecos "$fn" $user
+  sudo adduser --uid $uid --gid $gid --shell /bin/bash --disabled-password --gecos ',,,' $user
 
   sudo mkdir -p /home/$user/.ssh
   sudo chmod 700 /home/$user/.ssh
@@ -36,8 +39,7 @@ fi
 # Update authorized_keys
 keys=/home/$user/.ssh/authorized_keys
 sudo touch $keys
-sudo grep "$key" $keys
-if [ $? -ne 0 ]; then
+if ! sudo grep -q "$key" $keys; then
   sudo /bin/bash -c "echo $key >> $keys"
 fi
 sudo chmod 600 $keys
@@ -50,8 +52,7 @@ if [ ! -d $sudoersd ]; then
 fi
 
 admins="$sudoersd/admins"
-sudo grep $user $admins
-if [ $? -ne 0 ]; then
+if ! sudo grep -q $user $admins; then
   sudo bash -c "echo '$user       ALL=(ALL)      NOPASSWD: ALL' >> $admins"
 fi
 
